name: Docker build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image and tag it with the timestamp variable
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/sample-docker-project:${{ steps.timestamp.outputs.timestamp }} --rm

      # Export the image as a tarball artifact
      - name: Export image
        id: export-image
        run: |
          docker save -o /tmp/myimage.tar ${{ secrets.DOCKERHUB_USERNAME }}/sample-docker-project:${{ steps.timestamp.outputs.timestamp }}
        continue-on-error: true

      # Upload the image artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the image artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp

      # Load the image from the tarball
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
